POST http://localhost:5000/auth/register HTTP/1.1
Content-Type: application/json

{
    "username" : "raditya_am",
    "email" : "radityaaqil@gmail.com",
    "fullname" : "prrrikitiw",
    "password" : "aaaaaaaaA1!",
    "confirmPassword" : "aaaaaaaaA1!"
}

###

GET http://localhost:5000/auth/verified HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsInVzZXJuYW1lIjoicmFkaXR5YV9hbSIsImlhdCI6MTY0OTY2NzgxOSwiZXhwIjoxNjQ5Njc1MDE5fQ.GA02vGKJcGFNvMtXAAw6mUuKe0x6Z4D_mTJoUKYHrjE

{
    
}

###

POST http://localhost:5000/auth/sendemail-verified HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsInVzZXJuYW1lIjoicmFkaXR5YV9hbSIsInRpbWVjcmVhdGVkIjoxNjQ5MjUzMDM2MjE0LCJpYXQiOjE2NDkyNTMwMzYsImV4cCI6MTY0OTI2MDIzNn0.C3QYC2taALJlNANse5LMgaBwOBP_gmoLLMItWg9dyDs

{
    "id":24,
    "email":"radityaaqil@gmail.com",
    "username":"raditya_am"
}

###

POST http://localhost:5000/auth/login HTTP/1.1
Content-Type: application/json

{
    "username" : "realbarbarapalvin",
    "email" : "radityaaqil@gmail.com",
    "password" : "aaaaaaaaA1!"
}

###

POST http://localhost:5000/auth/login HTTP/1.1
Content-Type: application/json

{
    "username" : "realgigihadid",
    "email" : "funfungoodtime@gmail.com",
    "password" : "aaaaaaaaA1!"
}

###

GET http://localhost:5000/auth/verified HTTP/1.1
Content-Type: application/json

{
    "id" : 20
}

###

POST http://localhost:5000/auth/sendemail-verified HTTP/1.1
Content-Type: application/json

{
    "id" : "15",
    "username" : "myname"
}

###

GET http://localhost:5000/auth/keeplogin HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoicmFkaXR5YV9hbSIsImlhdCI6MTY0OTI0MjA5MiwiZXhwIjoxNjQ5MjQ5MjkyfQ.HOKiIWtYZv1SdC6jhjDc4p1wgHSX-aAHmYLuNw7oy_g

{

}

###

PATCH  http://localhost:5000/profile/updateprofile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsInVzZXJuYW1lIjoicmFkaXR5YV9hbSIsImlhdCI6MTY0OTY2NjMyNiwiZXhwIjoxNjQ5NjczNTI2fQ.LHb5bv5huMkWBSbUD1kkKFeBTkZfYRGYC0NcBNxiHhM

{
    "fullname" : "Sebastian Vettelszadadasadaddasd",
    "bio" : "4x WDC"
}

###

POST http://localhost:5000/post/postcaption HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsInVzZXJuYW1lIjoicmVhbGJhcmJhcmFwYWx2aW5uIiwiaWF0IjoxNjUwMjY2ODIwLCJleHAiOjE2NTAyNzQwMjB9.jJs3FJ23PR2p_sYRRF7KIp2-UOFrs6bo2oWd4PUvhd8

{
    "caption" : "Hasdasdasd"
}

###

POST http://localhost:5000/post/editpostcaption HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsInVzZXJuYW1lIjoicmVhbGJhcmJhcmFwYWx2aW4iLCJpYXQiOjE2NTAyMjY0NTEsImV4cCI6MTY1MDIzMzY1MX0.aOaxzVMv6KDrYc7VTaH9GVNIxwAnQ2HUesxbWL0bfUc

{
    "caption" : "cradadadadda",
    "id": 1
}

###

GET http://localhost:5000/post/getpost HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsInVzZXJuYW1lIjoicmVhbGJhcmJhcmFwYWx2aW5uIiwiaWF0IjoxNjUxMTQ2OTgyLCJleHAiOjE2NTExNjg1ODJ9.Vnp842EdnhjjcNtW3AQCwkv1MRU3EFkLh14SuK4sBLA

{
    
}

###

GET http://localhost:5000/post/getpostcount HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsInVzZXJuYW1lIjoicmVhbGJhcmJhcmFwYWx2aW5uIiwiaWF0IjoxNjUwNTQzNDIzLCJleHAiOjE2NTA1NTA2MjN9.mcBPZfVDOe1F-_ajOUS-yV19-BXrexKaXDaWg8KSzrg

{
    
}

###

GET http://localhost:5000/post/getuserpost HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsInVzZXJuYW1lIjoicmVhbGdpZ2loYWRpZCIsImlhdCI6MTY1MTI0MjMzMywiZXhwIjoxNjUxMjYzOTMzfQ.9iPpgMUvyxg9gvYOcitMBk-o5iQMqifjjMnzgxuFS6k

{
    
}

###

DELETE http://localhost:5000/post/deletepost/70 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsInVzZXJuYW1lIjoicmVhbGdpZ2loYWRpZCIsImlhdCI6MTY1MTAzMzA1MCwiZXhwIjoxNjUxMDU0NjUwfQ._axiOhwEv4y2Z3hlFqp-3fVYopnuQcddd_Gym7E26QY

{
    
}

###

GET http://localhost:5000/post/getuserpostdetail/60 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsInVzZXJuYW1lIjoicmVhbGdpZ2loYWRpZCIsImlhdCI6MTY1MDgwMTY2MCwiZXhwIjoxNjUwODIzMjYwfQ.uc228MMjLORaNSEgjJS189bwBbrK0pTTcT5mqSmOoK4

{
    
}

###

PATCH http://localhost:5000/post/editpostcaptionimage/60 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsInVzZXJuYW1lIjoicmVhbGdpZ2loYWRpZCIsImlhdCI6MTY1MDg4NjQ1MiwiZXhwIjoxNjUwOTA4MDUyfQ.S5zjARMoDsvC5w9B-Hd5QAkxQryu7jiphA7blwYv08w

{
  "caption" : "Hasdasdasd"
}

###

POST http://localhost:5000/post/addlikes/64 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsInVzZXJuYW1lIjoicmVhbGdpZ2loYWRpZCIsImlhdCI6MTY1MTAzMzA1MCwiZXhwIjoxNjUxMDU0NjUwfQ._axiOhwEv4y2Z3hlFqp-3fVYopnuQcddd_Gym7E26QY

{
    
}

###

POST http://localhost:5000/post/comments/63 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsInVzZXJuYW1lIjoicmVhbGdpZ2loYWRpZCIsImlhdCI6MTY1MTA2Mjg4MCwiZXhwIjoxNjUxMDg0NDgwfQ.LvcTHPyxYb1hl8zV33e9uL5kGt-6yIGO52_xU7_S5V0

{
    "comment" : "second comment"
}

###

GET http://localhost:5000/post/getcomments/63 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsInVzZXJuYW1lIjoicmVhbGdpZ2loYWRpZCIsImlhdCI6MTY1MTE1MTI2MiwiZXhwIjoxNjUxMTcyODYyfQ.WAe8lNewEtEkRDAuswBMgFj0OCc_iEPKr7NosbMkp9c

{
    
}

###

GET http://localhost:5000/post/getcommentscount/60 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsInVzZXJuYW1lIjoicmVhbGJhcmJhcmFwYWx2aW5uIiwiaWF0IjoxNjUxMTQ2OTgyLCJleHAiOjE2NTExNjg1ODJ9.Vnp842EdnhjjcNtW3AQCwkv1MRU3EFkLh14SuK4sBLA

{
    
}

###

GET http://localhost:5000/post/getusercomment HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsInVzZXJuYW1lIjoicmVhbGdpZ2loYWRpZCIsImlhdCI6MTY1MTI0MjMzMywiZXhwIjoxNjUxMjYzOTMzfQ.9iPpgMUvyxg9gvYOcitMBk-o5iQMqifjjMnzgxuFS6k

{
    
}

###

GET http://localhost:5000/post/getuserpostmedia HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsInVzZXJuYW1lIjoicmVhbGdpZ2loYWRpZCIsImlhdCI6MTY1MTI0MjMzMywiZXhwIjoxNjUxMjYzOTMzfQ.9iPpgMUvyxg9gvYOcitMBk-o5iQMqifjjMnzgxuFS6k

{
    
}

###

GET http://localhost:5000/post/getlikedpost HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDgsInVzZXJuYW1lIjoicmVhbGdpZ2loYWRpZCIsImlhdCI6MTY1MTI0MjMzMywiZXhwIjoxNjUxMjYzOTMzfQ.9iPpgMUvyxg9gvYOcitMBk-o5iQMqifjjMnzgxuFS6k

{
    
}